name: insta_assets_picker_demo
description: The demo project for the insta_assets_picker package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  insta_assets_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true